-- Migration: Create attendance and teacher tables
-- Run this in Supabase SQL Editor

-- ========================================
-- TEACHERS TABLE
-- ========================================
CREATE TABLE IF NOT EXISTS teachers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    subject TEXT NOT NULL,
    employee_id TEXT NOT NULL UNIQUE,
    role TEXT NOT NULL DEFAULT 'teacher' CHECK (role IN ('teacher', 'admin')),
    avatar TEXT DEFAULT '👨‍🏫',
    hire_date DATE,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create teachers indexes
CREATE INDEX IF NOT EXISTS idx_teachers_email ON teachers(email);
CREATE INDEX IF NOT EXISTS idx_teachers_employee_id ON teachers(employee_id);
CREATE INDEX IF NOT EXISTS idx_teachers_role ON teachers(role);

-- ========================================
-- ATTENDANCE SESSIONS TABLE
-- ========================================
CREATE TABLE IF NOT EXISTS attendance_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_name TEXT NOT NULL,
    section_id TEXT,
    created_by BIGINT REFERENCES teachers(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    is_active BOOLEAN DEFAULT true,
    expires_at TIMESTAMP WITH TIME ZONE
);

-- Create attendance sessions indexes
CREATE INDEX IF NOT EXISTS idx_attendance_sessions_active ON attendance_sessions(is_active);
CREATE INDEX IF NOT EXISTS idx_attendance_sessions_created_by ON attendance_sessions(created_by);

-- ========================================
-- ATTENDANCE RECORDS TABLE
-- ========================================
CREATE TABLE IF NOT EXISTS attendance_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL REFERENCES attendance_sessions(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL,
    student_name TEXT NOT NULL,
    grade TEXT NOT NULL,
    scanned_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    scan_method TEXT DEFAULT 'qr_code' CHECK (scan_method IN ('qr_code', 'manual')),
    status TEXT NOT NULL DEFAULT 'present' CHECK (status IN ('present', 'late', 'early'))
);

-- Create attendance records indexes
CREATE INDEX IF NOT EXISTS idx_attendance_records_session ON attendance_records(session_id);
CREATE INDEX IF NOT EXISTS idx_attendance_records_user ON attendance_records(user_id);
CREATE INDEX IF NOT EXISTS idx_attendance_records_scanned_at ON attendance_records(scanned_at);

-- ========================================
-- SAMPLE TEACHER DATA
-- ========================================
INSERT INTO teachers (id, name, email, password, subject, employee_id, role, avatar, hire_date, is_active)
VALUES 
    (1, 'John Smith', 'john.smith@school.edu', 'teacher123', 'Mathematics', 'EMP-001', 'admin', '👨‍🏫', '2020-08-15', true),
    (2, 'Emily Johnson', 'emily.johnson@school.edu', 'teacher123', 'Science', 'EMP-002', 'teacher', '👩‍🏫', '2021-01-10', true),
    (3, 'Michael Brown', 'michael.brown@school.edu', 'teacher123', 'English', 'EMP-003', 'teacher', '👨‍🏫', '2019-09-01', true)
ON CONFLICT (id) DO NOTHING;

-- ========================================
-- SAMPLE ATTENDANCE SESSION
-- ========================================
INSERT INTO attendance_sessions (id, session_name, section_id, created_by, is_active, expires_at)
VALUES 
    (1, 'Morning Check-in - ' || CURRENT_DATE::TEXT, '10-A', 1, true, NOW() + INTERVAL '12 hours')
ON CONFLICT (id) DO NOTHING;

-- ========================================
-- SAMPLE ATTENDANCE RECORDS
-- ========================================
INSERT INTO attendance_records (session_id, user_id, student_name, grade, status, scan_method)
VALUES 
    (1, 1, 'Alex Johnson', '10-A', 'present', 'qr_code'),
    (1, 2, 'Sarah Williams', '10-B', 'present', 'qr_code'),
    (1, 3, 'Mike Chen', '10-A', 'late', 'qr_code')
ON CONFLICT DO NOTHING;
