-- Migration: Unified Role-Based System
-- This migration adds role support to users and creates sections table

-- ========================================
-- ADD ROLE TO USERS TABLE
-- ========================================
ALTER TABLE users ADD COLUMN IF NOT EXISTS role TEXT NOT NULL DEFAULT 'student' CHECK (role IN ('student', 'teacher', 'admin'));
ALTER TABLE users ADD COLUMN IF NOT EXISTS section_id TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS employee_id TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS subject TEXT;

-- Create indexes for new columns
CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);
CREATE INDEX IF NOT EXISTS idx_users_section ON users(section_id);

-- ========================================
-- SECTIONS TABLE
-- ========================================
CREATE TABLE IF NOT EXISTS sections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_name TEXT NOT NULL UNIQUE,
    grade_level TEXT NOT NULL,
    adviser_id BIGINT REFERENCES teachers(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    is_active BOOLEAN DEFAULT true
);

-- Create sections indexes
CREATE INDEX IF NOT EXISTS idx_sections_name ON sections(section_name);
CREATE INDEX IF NOT EXISTS idx_sections_adviser ON sections(adviser_id);

-- ========================================
-- UPDATE EXISTING USERS WITH ROLES
-- ========================================
UPDATE users SET role = 'student' WHERE role IS NULL;

-- ========================================
-- SAMPLE SECTIONS DATA
-- ========================================
INSERT INTO sections (id, section_name, grade_level, adviser_id, is_active)
VALUES 
    (1, '10-A', 'Grade 10', 2, true),
    (2, '10-B', 'Grade 10', 3, true),
    (3, '11-A', 'Grade 11', 2, true)
ON CONFLICT (id) DO NOTHING;

-- ========================================
-- UPDATE USERS WITH SECTION
-- ========================================
UPDATE users SET section_id = '10-A' WHERE id = 1;
UPDATE users SET section_id = '10-B' WHERE id = 2;
UPDATE users SET section_id = '10-A' WHERE id = 3;
