-- Migration: Create activities table for tracking user activities
-- Run this in Supabase SQL Editor

-- ========================================
-- ACTIVITIES TABLE
-- ========================================
CREATE TABLE IF NOT EXISTS activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    type TEXT NOT NULL,
    description TEXT NOT NULL,
    points_earned INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create activities indexes
CREATE INDEX IF NOT EXISTS idx_activities_user_id ON activities(user_id);
CREATE INDEX IF NOT EXISTS idx_activities_created_at ON activities(created_at);

-- ========================================
-- SAMPLE ACTIVITIES DATA
-- ========================================
INSERT INTO activities (id, user_id, type, description, points_earned, created_at)
VALUES 
    (1, 1, 'quiz_complete', 'Completed Mathematics Quiz', 50, NOW() - INTERVAL '1 day'),
    (2, 2, 'assignment_submit', 'Submitted Science Project', 75, NOW() - INTERVAL '2 days'),
    (3, 3, 'attendance_present', 'Attended class on time', 10, NOW() - INTERVAL '3 hours'),
    (4, 1, 'streak_milestone', 'Reached 7-day streak!', 25, NOW() - INTERVAL '1 week'),
    (5, 2, 'points_earned', 'Earned bonus points for participation', 15, NOW() - INTERVAL '5 hours')
ON CONFLICT (id) DO NOTHING;
