-- Migration: Create recent_activities table for dashboard display
-- Run this in Supabase SQL Editor

-- ========================================
-- RECENT ACTIVITIES TABLE
-- ========================================
CREATE TABLE IF NOT EXISTS recent_activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    activity_type TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    icon TEXT DEFAULT 'fa-clock',
    icon_color TEXT DEFAULT '#4361ee',
    points INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for faster queries
CREATE INDEX IF NOT EXISTS idx_recent_activities_user_id ON recent_activities(user_id);
CREATE INDEX IF NOT EXISTS idx_recent_activities_created_at ON recent_activities(created_at DESC);

-- ========================================
-- SAMPLE RECENT ACTIVITIES DATA
-- ========================================
INSERT INTO recent_activities (id, user_id, activity_type, title, description, icon, icon_color, points, created_at)
VALUES 
    (1, 1, 'streak', 'Streak Milestone', 'Reached 7-day streak!', 'fa-fire', '#f97316', 25, NOW() - INTERVAL '1 day'),
    (2, 1, 'attendance', 'Attendance', 'Attended class on time', 'fa-calendar-check', '#4361ee', 10, NOW() - INTERVAL '2 days'),
    (3, 2, 'attendance', 'Attendance', 'Attended class on time', 'fa-calendar-check', '#4361ee', 10, NOW() - INTERVAL '3 days')
ON CONFLICT (id) DO NOTHING;
