-- Migration: Simplify Database Tables
-- This creates simpler, easier-to-manage tables for the attendance system
-- Run this in Supabase SQL Editor

-- ========================================
-- SIMPLE ACCOUNTS TABLE (replaces users + teachers)
-- ========================================
CREATE TABLE IF NOT EXISTS accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'student' CHECK (role IN ('student', 'teacher', 'admin')),
    section TEXT,
    subject TEXT,
    employee_id TEXT,
    avatar TEXT DEFAULT '👤',
    points INTEGER DEFAULT 0,
    streak INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    is_active BOOLEAN DEFAULT true
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_accounts_email ON accounts(email);
CREATE INDEX IF NOT EXISTS idx_accounts_role ON accounts(role);
CREATE INDEX IF NOT EXISTS idx_accounts_section ON accounts(section);

-- ========================================
-- SIMPLE SECTIONS TABLE
-- ========================================
CREATE TABLE IF NOT EXISTS school_sections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    grade_level TEXT,
    adviser TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    is_active BOOLEAN DEFAULT true
);

-- Create index
CREATE INDEX IF NOT EXISTS idx_school_sections_name ON school_sections(name);

-- ========================================
-- SAMPLE ACCOUNTS DATA (Replace with your own!)
-- ========================================
INSERT INTO accounts (name, email, password, role, section, subject, employee_id, avatar, points) VALUES
    -- Admin
    ('Admin User', 'admin@school.edu', 'admin123', 'admin', NULL, NULL, 'ADM-001', '👨‍💼', 0),
    
    -- Teachers
    ('Mr. Smith', 'smith@school.edu', 'teacher123', 'teacher', NULL, 'Mathematics', 'TCH-001', '👨‍🏫', 0),
    ('Ms. Johnson', 'johnson@school.edu', 'teacher123', 'teacher', NULL, 'Science', 'TCH-002', '👩‍🏫', 0),
    ('Mrs. Brown', 'brown@school.edu', 'teacher123', 'teacher', NULL, 'English', 'TCH-003', '👩‍🏫', 0),
    
    -- Students (Section: 12-Gosling)
    ('Juan dela Cruz', 'juan@school.edu', 'student123', 'student', '12-Gosling', NULL, NULL, '👨‍🎓', 100),
    ('Maria Santos', 'maria@school.edu', 'student123', 'student', '12-Gosling', NULL, NULL, '👩‍🎓', 150),
    ('Pedro Garcia', 'pedro@school.edu', 'student123', 'student', '12-Gosling', NULL, NULL, '👨‍🎓', 80),
    ('Ana Reyes', 'ana@school.edu', 'student123', 'student', '12-Gosling', NULL, NULL, '👩‍🎓', 120),
    ('Luis Martinez', 'luis@school.edu', 'student123', 'student', '12-Gosling', NULL, NULL, '👨‍🎓', 90)
ON CONFLICT (email) DO NOTHING;

-- ========================================
-- SAMPLE SECTIONS DATA
-- ========================================
INSERT INTO school_sections (name, grade_level, adviser) VALUES
    ('12-Gosling', 'Grade 12', 'Mr. Smith'),
    ('11-Einstein', 'Grade 11', 'Ms. Johnson'),
    ('10-Newton', 'Grade 10', 'Mrs. Brown')
ON CONFLICT (name) DO NOTHING;

-- ========================================
-- ATTENDANCE TABLE (Simplified)
-- ========================================
CREATE TABLE IF NOT EXISTS attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT REFERENCES accounts(id) ON DELETE CASCADE,
    student_name TEXT NOT NULL,
    section TEXT NOT NULL,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    status TEXT NOT NULL DEFAULT 'present' CHECK (status IN ('present', 'late', 'absent', 'excused')),
    time_in TIME NOT NULL DEFAULT CURRENT_TIME,
    teacher_id BIGINT REFERENCES accounts(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_attendance_date ON attendance(date);
CREATE INDEX IF NOT EXISTS idx_attendance_section ON attendance(section);
CREATE INDEX IF NOT EXISTS idx_attendance_student ON attendance(student_id);
